- test/tests/materials/decomposition/no_decomp.i
- test/tests/materials/decomposition/strain_spectral.i
changed damage from variable to auxvariable to decouple it from the system
> modify tests for decomposition

- .travis.yml
- include/executioners/FixedPointSolve.h
> add macosx matrix in travis

- include/ics/BrittleDamageIC.h
- include/materials/ADDegradedElasticStressBase.h
- include/materials/CNHDegradedElasticPlasticPK1StressBase.h
- include/materials/CoalescenceEnergy.h
- include/materials/NoDegradation.h
- include/userobjects/MaterialPropertyUserObject.h
- src/ics/BrittleDamageIC.C
- src/materials/ADDegradedElasticStressBase.C
- src/materials/CNHDegradedElasticPlasticPK1StressBase.C
- src/materials/CNHDegradedElasticPlasticPK1Stress_LinearHardening_StrictlyDissipative.C
- src/materials/CoalescenceEnergy.C
- src/materials/NoDegradation.C
- src/materials/SmallStrainDegradedElasticPK2Stress_NoSplit.C
- src/materials/SmallStrainDegradedElasticPK2Stress_StrainSpectral.C
- src/materials/SmallStrainDegradedElasticPK2Stress_StrainVolDev.C
- src/userobjects/MaterialPropertyUserObject.C
- test/tests/ductile_homogenized/compare_c_viscous/elastic_plastic_fracture.i
> enable a completely decoupled staggered scheme

- include/materials/large_deformation_models/ComputeDeformationGradient.h
- include/materials/large_deformation_models/ComputeLargeDeformationStress.h
- include/materials/large_deformation_models/HenckyIsotropicElasticity.h
- include/materials/large_deformation_models/LargeDeformationElasticityModel.h
- include/materials/large_deformation_models/LargeDeformationJ2Plasticity.h
- include/materials/large_deformation_models/LargeDeformationPlasticityModel.h
- include/utils/RaccoonUtils.h
- src/materials/large_deformation_models/ComputeDeformationGradient.C
- src/materials/large_deformation_models/ComputeLargeDeformationStress.C
- src/materials/large_deformation_models/HenckyIsotropicElasticity.C
- src/materials/large_deformation_models/LargeDeformationElasticityModel.C
- src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
- src/materials/large_deformation_models/LargeDeformationPlasticityModel.C
- src/utils/RaccoonUtils.C
- test/tests/tutorials/large_deformation/elasticity.i
- test/tests/tutorials/large_deformation/elastoplasticity.i
Add Hencky type model and J2 plasticity exponential update.
> Large deformation elasticity and plasticity

- include/utils/RaccoonUtils.h
- src/utils/RaccoonUtils.C
Fix compile error in RaccoonUtils
> Use Eigen eigenvalue decomposition (it is faster)

- doc/content/source/materials/large_deformation_models/HenckyIsotropicElasticity.md
- include/materials/large_deformation_models/HenckyIsotropicElasticity.h
- src/materials/large_deformation_models/HenckyIsotropicElasticity.C
Added spectral and Voldev split to HeckyIsotropicElasticity
Closes #84
> Added Spectral and VolDev Split to Hencky Model

- include/materials/large_deformation_models/ComputeLargeDeformationStress.h
- include/materials/small_deformation_models/ComputeSmallDeformationStress.h
- src/materials/ComputeEigenstrainFromFunctionInitialStress.C
- Update submodule
- Fix several typos
refs #86
> Update submodule moose

- include/materials/large_deformation_models/LargeDeformationElasticityModel.h
- tutorials/homogeneous_cube/CNH_J2_powerlawhardening/elastoplasticity_fracture.i
> Minor doco fix

- doc/content/tutorials/08_ductile_fracture.md
Issue #45 
Added tutorial 08 for ductile fracture. 
The tutorial covers linear hardening with hencky isotropic elasticity
> Ductiletutorial

- .github/workflows/clang_format.yml
- src/materials/hardening_models/LinearHardening.C
This fixes the stress envelope of `LinearHardening`. The degradation now applies to the entire thing.
> Fix linear hardening

- include/kernels/ADCoefMatDiffusion.h
- include/kernels/ADPFFDiffusion.h
- src/kernels/ADCoefMatDiffusion.C
- src/kernels/ADPFFDiffusion.C
> Correct residuals in rz

- src/base/raccoonApp.C
- src/base/raccoonAppTypes.C
Closes #127
@hugary1995 this'll come with a manual submodule update once I merge https://github.com/idaholab/moose/pull/20989 in moose. Are you around to get this in today?
> Use new static exec flag registration

- src/base/raccoonApp.C
- src/main.C
- src/materials/large_deformation_models/ComputeDeformationGradient.C
- test/src/base/raccoonTestApp.C
- unit/src/main.C
Adapt to the new changes in MOOSE(https://github.com/idaholab/moose/pull/25994)
> Clean up main.C and explicitly register dependent app

- src/utils/RaccoonUtils.C
Forward compatibility with idaholab/moose#27582
> Simplifying AD headers

- src/materials/hardening_models/JohnsonCookHardening.C
- src/materials/large_deformation_models/LargeDeformationJ2Plasticity.C
#166 
Fixes to heat generation with rate dependent model. Fixing /0 issues that may pop up.
> Fixes for heat /0 cases for rate dependent hardening models

- tutorials/three_point_bending/elastoplasticity.i
> updating userobject block to instead be MeshModifiers block in 3 bending tutorial

- Makefile
> Removing extra solid_mechanics option in makefile #000

- test/tests/hardening_models/elastoplasticity.i
- tutorials/homogeneous_cube/Hencky_J2_JohnsonCook/elastoplasticity.i
- tutorials/homogeneous_cube/Hencky_J2_arrheniuslawhardening/elastoplasticity.i
- tutorials/homogeneous_cube/Hencky_J2_arrheniuslawhardening_creep/elastoplasticity.i
- tutorials/homogeneous_cube/Hencky_J2_arrheniuslawhardening_creep_thermal/elastoplasticity.i
- tutorials/homogeneous_cube/Hencky_J2_linearhardening/elastoplasticity.i
> removed trailing ; from cli_args

- src/bcs/LoadingUnloadingDirichletBC.C
> More inclusion of what we use

- test/tests/nucleation_models/klbf.i
- test/tests/nucleation_models/klr.i
- tutorials/surfing_boundary_problem/fracture.i
> Remove inactive output_material_properties causing warnings

- test/tests/nucleation_models/elasticity.i
- tutorials/surfing_boundary_problem/elasticity.i
> Remove more unused parameters

- .github/workflows/build_docs.yml
> increasing fetch depth for doc build workflow #203

- doc/content/getting_started/update.md
> change to update instructions

- src/materials/nucleation_models/LDLNucleationMicroForce.C
> modify drive force H(I1)
